### ISSUE TITLE
Limit of 1 tag per page

### ISSUE THREAD

**Issue by stijnswinnen** [OleVik/grav-theme-project-space#5]
It seems there's a limit of 1 tag per page. Is this correct and can this be changed?

**Comment by OleVik** [comment]
The amount of tags applied per page is only limited by the amount of tags and their length, as limited by the browser's maximum GET query. For example, the URL `http://writing.local/projects/tag:X2+-+Cohesive+actors,C1+-+Confounder` applies the tags `X2 - Cohesive actors` and `C1 - Confounder`. The same applies to all other taxonomies used by the theme.

Are you having issues applying more than 1 tag?

**Comment by stijnswinnen** [comment]
Thank you for the fast reply. After investigating the issue more, it might indeed be another reason related to the admin panel.
What I notice I do can add more than 1 tag when working in expert mode. The issue is in Normal mode only 1 tag is displayed. So when doing an update of an existing page in Normal mode, the number of tags gets reduced to 1.

**Comment by OleVik** [comment]
The issue is probably upstream, with how Admin handles the `selectize`-field. It seems this was resolved with [1461](https://github.com/getgrav/grav-plugin-admin/issues/1461), through [a related commit](https://github.com/getgrav/grav-plugin-admin/commit/08461e51e0e94cba6e2028651c88c55e13649b9d).

Could you try editing post.yaml in the theme's /blueprints, and adding in `merge_items: true` anywhere in the [selectize-field](https://github.com/OleVik/grav-theme-project-space/blob/master/blueprints/post.yaml#L76-L82) declaration?

**Comment by stijnswinnen** [comment]
At first sight it doesn't seem to change anything. Changed the setting, cleared cache and signed in again,
 Following the same workflow. the issue remains. First save in expert mode to save several tags. switched to Normal mode and saved again to result in loos of all but the first tag.

saved in Expert mode, several tags
<img width="422" alt="screen shot 2019-02-17 at 22 33 27" src="https://user-images.githubusercontent.com/5034472/52919624-98536a00-3304-11e9-8740-57c46dd77f69.png">
Saved in Normal mode, only 1 tag,
<img width="434" alt="screen shot 2019-02-17 at 22 33 44" src="https://user-images.githubusercontent.com/5034472/52919623-97bad380-3304-11e9-887b-d91632473919.png">

**Comment by OleVik** [comment]
I'll run some tests and see if I can replicate the issue.

**Comment by OleVik** [comment]
The issue is indeed upstream on the Admin-side, the tags are loaded initially but cleared out when the JS initiates. That is to say, you can still use multiple tags from the Admin, and save them, but once the page reloads they are replaced with just 1. If you do not save again, the original selected tags are still kept in the Markdown-file, however - unless you save again with just the 1.

**Comment by OleVik** [comment]
This is fixed with Grav v1.6.0-rc.2 and Admin v1.9.0-rc.2, as the fix with `merge_items` was added in Admin v1.9.0-beta.7. So you'll either have to make due until they both become stable, or upgrade to the testing releases.

**Comment by stijnswinnen** [comment]
Thank you for the update!
